---
swagger: "2.0"
info:
  version: "0.1"
  title: "sample-serverless"
schemes:
- "https"
paths:
  /hellos:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            \$ref: "#/definitions/Hellos"
        408:
          description: "timed out"
        500:
          description: "internal server eorror"

definitions:
  Hellos:
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          \$ref: '#/definitions/Hello'
  Hello:
    type: object
    required:
      - message
    properties:
      message:
        type: string
